FROM jenkins/jenkins:lts

USER root

# Устанавливаем Docker CLI
RUN apt-get update && apt-get install -y docker.io

# Добавим пользователя jenkins в группу docker
RUN usermod -aG docker jenkins

USER jenkins
